---
title: "Week 7"
subtitle: "Descriptives"
date: "`r Sys.Date()`"
author: "Michael W. Kearney, PhD"
institute: |
  | School of Journalism
  | Informatics Institute
  | University of Missouri
output: uslides::uslides_html
---


# Recap and overview

## #rstats
> + **R environment**
>     - A statistical programming language
> + **Rstudio**
>     - A graphical interface (development environment)
> + **R objects and classes**
>     - Creating and editing objects
>     - Classes: `numeric`, `integer`, `character`, `factor`, `data.frame`
> + **R functions**
>     - Named automated tasks used on data (e.g., `mean(x)`)


## Due today
+ Upload output from Homework #1

## Overview
+ **Descriptives**: summarizing data
    - Measures of central tendency
    - Measures of dispersions
+ Getting data *into* R
    - Reading different types of data files
+ Descriptives in **R**
    - Summary functions/packages
    - Automating outputs

# Descriptives

## "Statistics"
+ **Descriptive** statistics (AKA *parametrics*)
    - Describing the population of data
    - Not a lot of probability theory required
+ **Inferential** statistics (AKA *statistics*)
    - Describing the population using a sample of data
    - Probability theory is key

# Getting data into R

# DescRiptives

