---
title: "Journalism Studies Articles"
subtitle: "Abstracts"
date: "`r Sys.Date()`"
author: "Michael W. Kearney, PhD"
institute: | 
  | School of Journalism
  | Informatics Institute
  | University of Missouri
output: uslides::uslides_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, size = "\\scriptsize")
```

## Abstract

\scriptsize

Constanza Mujica, C. & Bachmann, I. (2018). The impact of melodramatic news coverage on information recall and comprehension. *Journalism Studies, 19*, 334-352. doi:10.1080/1461670X.2016.1190661

&nbsp;

\small

In many countries, television newscasts are increasingly relying on personalization and emotion exacerbation in their news coverage, arguably as a means to attract audiences. Such features are prominent in Latin American cultural products based on melodrama, such as telenovelas. While often deemed to be bad journalism, there is mixed evidence on the impact of such news treatment on knowledge acquisition, especially with audiences more attuned to these formats. Based on an experiment in Chile, this study tests the effects of melodramatic coverage on viewers’ recall and comprehension of news items. Results show that melodramatic treatment favors recall, but not comprehension of data included in the news reports. Comparisons across news treatment by gender, age group, and socio-economic status suggest that rather than overall differences, specific demographic groups are more affected by melodramatic news.


## Abstract

\scriptsize

Gil de Zúñiga, H., Diehl, T., & Ardèvol-Abreu, A. (2018).*When citizens and journalists interact on Twitter
expectations of journalists' performance on social media and perceptions of media bias. *Journalism Studies, 18*, 227-246. doi:10.1080/1461670X.2016.1178593 


&nbsp;

\small

Twitter has become the leading social media platform for journalists to break news, build a following, and interact with the public. Social media offer journalists and citizens a communication space, where they can discuss issues, provide context for the news, and foster community values. This study examines how expectations about journalistic practices on social media influence audience engagement with journalists, and in turn, perceptions of editorial bias. Drawing on a two-wave panel survey from the United States, we first find that expectations about the practice of “good journalism” on social media predict engagement with journalists on Twitter. Second, these personal interactions lead to lower levels of perceived bias in the news media. Finally, expectations of journalists’ performance on social media are explored as a moderator of perceived editorial bias. This study adds to the growing literature analyzing the causes and outcomes of audience engagement with journalists on social media.
